#!/usr/bin/env bash

export CONTECO_LABEL="backup.internal - Conteco"
export CONTECO_DESCRIPTION="Backup of all repositories of the non-external images of the ContEco ecosystem."

export CONTECO_TYPE="backup"
export CONTECO_NAME="internal"
export CONTECO_TAG="20200731"

export CONTECO_BASE="external.bash:5.0.18"
export CONTECO_BUILD="image-base"
