---
version: '3'
services:

# START SERVICE backup.internal
  backup:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.backup.internal:20200527
    environment: []
    command: [${CONTECO_DC_BACKUP_COMMAND}]
    volumes: [${CONTECO_DC_BACKUP_VOLUMES}]
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${CONTECO_DC_BACKUP_DEPLOY_MODE}
      replicas: ${CONTECO_DC_BACKUP_DEPLOY_REPLICAS}
      resources:
        limits:
          cpus: '${CONTECO_DC_BACKUP_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_BACKUP_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_BACKUP_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_BACKUP_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${CONTECO_DC_BACKUP_DEPLOY_PLACEMENT_CONSTRAINTS}]
      labels: [${CONTECO_DC_BACKUP_DEPLOY_LABELS}]
    labels: [${CONTECO_DC_BACKUP_LABELS}]
# END SERVICE backup.internal

volumes: {}
networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
